# Generated by Django 5.2.12 on 2026-04-13 08:50

import django.db.models.deletion
import mojo.models.rest
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0039_group_auth_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubInstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mojo_secrets', models.TextField(blank=True, default=None, null=True)),
                ('installation_id', models.BigIntegerField(db_index=True, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_installs', to='account.group')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
