# Generated by Django 4.2.21 on 2025-08-27 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mojo.models.rest


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, help_text='Task UUID without dashes', max_length=32)),
                ('task_function', models.CharField(db_index=True, help_text='Full function path (module.function)', max_length=255)),
                ('task_channel', models.CharField(db_index=True, default='default', help_text='Task channel name', max_length=100)),
                ('event_type', models.CharField(choices=[('created', 'Task Created'), ('status_change', 'Status Changed'), ('started', 'Task Started'), ('completed', 'Task Completed'), ('error', 'Task Error'), ('cancelled', 'Task Cancelled'), ('expired', 'Task Expired'), ('retry', 'Task Retry')], db_index=True, help_text='Type of event being logged', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, help_text='Current task status', max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], help_text='Previous task status', max_length=20, null=True)),
                ('runner_hostname', models.CharField(blank=True, db_index=True, help_text='Hostname of the runner executing the task', max_length=255, null=True)),
                ('thread_id', models.BigIntegerField(blank=True, help_text='Thread ID executing the task', null=True)),
                ('task_created_at', models.DateTimeField(blank=True, db_index=True, help_text='When the task was originally created', null=True)),
                ('task_started_at', models.DateTimeField(blank=True, help_text='When the task started executing', null=True)),
                ('task_completed_at', models.DateTimeField(blank=True, help_text='When the task completed', null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=3, help_text='Task execution duration in seconds', max_digits=10, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if task failed', null=True)),
                ('error_traceback', models.TextField(blank=True, help_text='Full error traceback', null=True)),
                ('task_data', models.JSONField(blank=True, help_text='Task data and parameters', null=True)),
                ('result_data', models.JSONField(blank=True, help_text='Task result data', null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When the task expires', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('max_retries', models.IntegerField(default=0, help_text='Maximum retry attempts allowed')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this log entry was created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='When this log entry was last modified')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the task', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['task_id', '-created'], name='tasks_taskl_task_id_bceb9b_idx'), models.Index(fields=['task_function', '-created'], name='tasks_taskl_task_fu_80c384_idx'), models.Index(fields=['task_channel', 'status'], name='tasks_taskl_task_ch_54f6ce_idx'), models.Index(fields=['event_type', '-created'], name='tasks_taskl_event_t_f68cc6_idx'), models.Index(fields=['status', '-created'], name='tasks_taskl_status_18f4b2_idx'), models.Index(fields=['runner_hostname', '-created'], name='tasks_taskl_runner__122857_idx')],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
