# Generated by Django 5.2.16 on 2026-08-06 21:44

import django.db.models.deletion
import mojo.models.rest
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0049_bouncersignal_account_bou_ip_addr_e101ed_idx'),
        ('dnsman', '0003_alter_domain_provider_acmedelegation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('http', 'HTTP host and port'), ('unix', 'Unix domain socket')], default='http', help_text='http | unix', max_length=16)),
                ('host', models.CharField(blank=True, default=None, help_text='kind=http only. Hostname or IPv4 address; never a URL.', max_length=253, null=True)),
                ('port', models.IntegerField(blank=True, default=None, help_text='kind=http only.', null=True)),
                ('socket_path', models.CharField(blank=True, default=None, help_text='kind=unix only. Must resolve under EDGE_SOCKET_BASE.', max_length=255, null=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('group', models.ForeignKey(blank=True, default=None, help_text='Null for a house upstream every tenant may select.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edge_upstreams', to='account.group')),
            ],
            options={
                'db_table': 'edge_upstream',
                'ordering': ['name'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='Vhost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('label', models.CharField(blank=True, default='', help_text="'' serves the apex, '*' the wildcard, else one DNS label.", max_length=63)),
                ('kind', models.CharField(choices=[('static', 'Static files'), ('spa', 'Single-page app (history fallback)'), ('proxy', 'Reverse proxy to a declared upstream')], default='static', help_text='static | spa | proxy', max_length=16)),
                ('pool', models.CharField(db_index=True, default='default', help_text='Which fleet pool serves this vhost. Nodes poll by pool.', max_length=32)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('certificate', models.ForeignKey(help_text='Must belong to this domain and cover the server name.', on_delete=django.db.models.deletion.PROTECT, related_name='vhosts', to='dnsman.certificate')),
                ('domain', models.ForeignKey(help_text='Owns the name. Tenancy resolves through this.', on_delete=django.db.models.deletion.CASCADE, related_name='vhosts', to='dnsman.domain')),
                ('upstream', models.ForeignKey(blank=True, default=None, help_text='Required for kind=proxy, forbidden otherwise.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vhosts', to='edge.upstream')),
            ],
            options={
                'db_table': 'edge_vhost',
                'ordering': ['domain', 'label'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.AddConstraint(
            model_name='upstream',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='edge_upstream_group_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='upstream',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', True)), fields=('name',), name='edge_upstream_house_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='upstream',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('host__isnull', False), ('kind', 'http'), ('port__isnull', False), ('socket_path__isnull', True)), models.Q(('host__isnull', True), ('kind', 'unix'), ('port__isnull', True), ('socket_path__isnull', False)), _connector='OR'), name='edge_upstream_kind_fields'),
        ),
        migrations.AddIndex(
            model_name='vhost',
            index=models.Index(fields=['pool', 'is_enabled'], name='edge_vhost_pool_2c8de1_idx'),
        ),
        migrations.AddIndex(
            model_name='vhost',
            index=models.Index(fields=['certificate', 'is_enabled'], name='edge_vhost_certifi_a3c142_idx'),
        ),
        migrations.AddConstraint(
            model_name='vhost',
            constraint=models.UniqueConstraint(condition=models.Q(('is_enabled', True)), fields=('domain', 'label'), name='edge_vhost_unique_enabled_server_name'),
        ),
        migrations.AddConstraint(
            model_name='vhost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'proxy'), ('upstream__isnull', False)), models.Q(models.Q(('kind', 'proxy'), _negated=True), ('upstream__isnull', True)), _connector='OR'), name='edge_vhost_kind_upstream'),
        ),
    ]
