# Generated by Django 5.2.16 on 2026-08-06 22:09

import django.db.models.deletion
import mojo.models.rest
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_bouncersignal_account_bou_ip_addr_e101ed_idx'),
        ('edge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('slug', models.CharField(db_index=True, help_text='Human label for this site. NOT a filesystem path.', max_length=64)),
                ('bucket', models.CharField(help_text='Must be one of EDGE_RELEASE_BUCKETS. Never caller-chosen.', max_length=255)),
                ('prefix', models.CharField(help_text='DERIVED from group and id. Never caller-supplied.', max_length=255)),
                ('auto_promote', models.BooleanField(default=False, help_text='Whether a verified upload goes live without a human.')),
                ('api_key', models.OneToOneField(blank=True, default=None, help_text='The CI credential allowed to register releases for this site. One key per site, enforced by the schema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_app', to='account.apikey')),
                ('group', models.ForeignKey(help_text='Owns this site. Explicit, because vhost may be null.', on_delete=django.db.models.deletion.CASCADE, related_name='web_apps', to='account.group')),
                ('vhost', models.OneToOneField(blank=True, default=None, help_text="Null for a site served elsewhere (e.g. CloudFront). Such a site is registerable and rollbackable but never appears in a node's desired state.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_app', to='edge.vhost')),
            ],
            options={
                'db_table': 'edge_web_app',
                'ordering': ['slug'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='WebAppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('version', models.CharField(db_index=True, help_text='Build id or git SHA. Immutable and unique per site.', max_length=128)),
                ('manifest', models.JSONField(blank=True, default=list, help_text='[{path, size, sha256}] — declared by CI before upload, verified against S3 before the release becomes promotable.')),
                ('status', models.CharField(choices=[('pending', 'Registered, upload not verified'), ('uploaded', 'Verified in S3, not promoted'), ('live', 'Serving'), ('superseded', 'Was live, retained for rollback')], db_index=True, default='pending', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_app_releases', to=settings.AUTH_USER_MODEL)),
                ('webapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='edge.webapp')),
            ],
            options={
                'db_table': 'edge_web_app_release',
                'ordering': ['-created'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.AddField(
            model_name='webapp',
            name='current_release',
            field=models.ForeignKey(blank=True, default=None, help_text='What nodes should be serving. Rollback repoints this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='edge.webapprelease'),
        ),
        migrations.AddIndex(
            model_name='webapprelease',
            index=models.Index(fields=['webapp', 'status'], name='edge_web_ap_webapp__19f737_idx'),
        ),
        migrations.AddConstraint(
            model_name='webapprelease',
            constraint=models.UniqueConstraint(fields=('webapp', 'version'), name='edge_release_webapp_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='webapp',
            constraint=models.UniqueConstraint(fields=('group', 'slug'), name='edge_webapp_group_slug_uniq'),
        ),
    ]
