# Hand-ordered. Generated by Django 5.2.16, then rearranged so the kind remap
# runs BETWEEN the old constraint's removal and the new one's addition —
# existing rows carry the old kind strings, and adding `edge_vhost_kind_fields`
# before remapping them would fail on every proxy row.
#
# Kind remap: proxy -> api, spa -> site + spa=True, static -> site.
#
# The reverse remap is LOSSY once site_api or redirect rows exist: neither has
# an old kind to return to, so those rows keep their new kind strings (the old
# CheckConstraint tolerates them — both carry a NULL upstream). Reversing past
# this migration is for backing out the upgrade, not for round-tripping data.

import django.db.models.deletion
import mojo.models.rest
from django.db import migrations, models


def remap_kinds_forward(apps, schema_editor):
    # queryset.update on purpose: historical models have no save() and the
    # validators must not run here — they would refuse rows that were legal
    # under the old rules (and would hit settings lookups mid-migration).
    Vhost = apps.get_model("edge", "Vhost")
    Vhost.objects.filter(kind="proxy").update(kind="api")
    Vhost.objects.filter(kind="spa").update(kind="site", spa=True)
    Vhost.objects.filter(kind="static").update(kind="site")


def remap_kinds_reverse(apps, schema_editor):
    Vhost = apps.get_model("edge", "Vhost")
    Vhost.objects.filter(kind="api").update(kind="proxy")
    Vhost.objects.filter(kind="site", spa=True).update(kind="spa")
    Vhost.objects.filter(kind="site").update(kind="static")
    # site_api / redirect rows are left as-is — lossy, see the module docstring.


class Migration(migrations.Migration):

    dependencies = [
        ('dnsman', '0003_alter_domain_provider_acmedelegation'),
        ('edge', '0002_webapp_webapprelease_webapp_current_release_and_more'),
    ]

    operations = [
        # 1. Drop the old kind/upstream pairing so rows can be remapped.
        migrations.RemoveConstraint(
            model_name='vhost',
            name='edge_vhost_kind_upstream',
        ),
        # 2. The new knobs. `spa` must exist before the remap writes it.
        migrations.AddField(
            model_name='vhost',
            name='body_size_mb',
            field=models.IntegerField(default=50, help_text="client_max_body_size, in megabytes (1-4096). Always rendered — nginx's 1m default is never silently in play."),
        ),
        migrations.AddField(
            model_name='vhost',
            name='claims_reserved',
            field=models.BooleanField(default=False, help_text='Platform-only override letting a HOUSE vhost claim a name on the reserved list. Set via POST edge/vhost/claim_reserved, never writable over plain REST.'),
        ),
        migrations.AddField(
            model_name='vhost',
            name='quiet_paths',
            field=models.JSONField(blank=True, default=list, help_text='api/site_api only: exact request paths kept out of the main access log (health checks). Each is whitelist-checked.'),
        ),
        migrations.AddField(
            model_name='vhost',
            name='redirect_to',
            field=models.CharField(blank=True, default=None, help_text='redirect only: target HOST (FQDN, validated as a server name — never a free URL).', max_length=253, null=True),
        ),
        migrations.AddField(
            model_name='vhost',
            name='serve_static',
            field=models.BooleanField(default=False, help_text="api/site_api only: serve the fleet's Django static root at /static/ instead of proxying it."),
        ),
        migrations.AddField(
            model_name='vhost',
            name='spa',
            field=models.BooleanField(default=False, help_text='site/site_api only: history-fallback to index.html instead of a 404.'),
        ),
        migrations.AlterField(
            model_name='vhost',
            name='kind',
            field=models.CharField(choices=[('api', 'Whole-host reverse proxy to a declared upstream'), ('site', 'Static site / single-page app'), ('site_api', 'Static site with proxied path prefixes'), ('redirect', 'Permanent redirect to another host')], default='site', help_text='api | site | site_api | redirect', max_length=16),
        ),
        migrations.AlterField(
            model_name='vhost',
            name='upstream',
            field=models.ForeignKey(blank=True, default=None, help_text='Required for kind=api, forbidden otherwise (site_api proxies per-route, never whole-host).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vhosts', to='edge.upstream'),
        ),
        # 3. The route table.
        migrations.CreateModel(
            name='VhostRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('path_prefix', models.CharField(help_text='Request-path prefix to proxy (e.g. /api). Whitelist-checked; never nginx syntax.', max_length=128)),
                ('upstream', models.ForeignKey(help_text='Where this prefix proxies. Platform-declared rows only.', on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='edge.upstream')),
                ('vhost', models.ForeignKey(help_text='The site_api vhost this prefix belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='edge.vhost')),
            ],
            options={
                'db_table': 'edge_vhost_route',
                'ordering': ['vhost', 'path_prefix'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.AddConstraint(
            model_name='vhostroute',
            constraint=models.UniqueConstraint(fields=('vhost', 'path_prefix'), name='edge_route_vhost_prefix_uniq'),
        ),
        # 4. Remap existing rows onto the new kind vocabulary.
        migrations.RunPython(remap_kinds_forward, remap_kinds_reverse),
        # 5. Only now can the new pairing be enforced.
        migrations.AddConstraint(
            model_name='vhost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'api'), ('redirect_to__isnull', True), ('upstream__isnull', False)), models.Q(('kind__in', ('site', 'site_api')), ('redirect_to__isnull', True), ('upstream__isnull', True)), models.Q(('kind', 'redirect'), ('redirect_to__isnull', False), ('upstream__isnull', True)), _connector='OR'), name='edge_vhost_kind_fields'),
        ),
    ]
