# Generated by Django 5.2.16. Drops the reserved-name house override along with
# the EDGE_RESERVED_SERVER_NAMES mechanism it suspended (#1646) — naming a vhost
# is Domain ownership plus manage_dns now, not a reservation list.
#
# **The reverse is LOSSY.** Reversing re-adds the column with default=False on
# every row, discarding which vhosts actually held a claim; the flag is not
# recoverable from anything else in the schema. Reversing past this migration is
# for backing out the upgrade, not for round-tripping data.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0004_blocklist_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vhost',
            name='claims_reserved',
        ),
    ]
