# Generated by Django 5.2.16 on 2026-08-09 22:47

import django.db.models.deletion
import mojo.models.rest
from django.db import migrations, models


def enable_existing_webapps(apps, schema_editor):
    apps.get_model('edge', 'WebApp').objects.update(auto_promote=True)


def restore_manual_default(apps, schema_editor):
    apps.get_model('edge', 'WebApp').objects.update(auto_promote=False)


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0005_remove_vhost_claims_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapp',
            name='auto_promote',
            field=models.BooleanField(default=True, help_text='Deploy a verified upload automatically. Disable only for an explicit manual-hold workflow.'),
        ),
        migrations.RunPython(enable_existing_webapps, restore_manual_default),
        migrations.CreateModel(
            name='WebAppDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('started', models.DateTimeField(blank=True, default=None, null=True)),
                ('finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('release_previous_status', models.CharField(blank=True, default='', help_text='Target release status restored when deployment rolls back.', max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('deploying', 'Deploying'), ('live', 'Live on the active fleet'), ('rolling_back', 'Rolling back'), ('rolled_back', 'Rolled back'), ('failed', 'Failed'), ('superseded', 'Superseded by a newer deployment')], db_index=True, default='queued', max_length=20)),
                ('targets', models.JSONField(blank=True, default=list, help_text='Active-runner snapshot and direct job ids for deployment.')),
                ('rollback_targets', models.JSONField(blank=True, default=list, help_text='Direct job ids used to restore the prior desired release.')),
                ('detail', models.TextField(blank=True, default='')),
                ('previous_release', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_deployments', to='edge.webapprelease')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='edge.webapprelease')),
                ('webapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='edge.webapp')),
            ],
            options={
                'db_table': 'edge_web_app_deployment',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['webapp', 'status'], name='edge_web_ap_webapp__56b6d2_idx'), models.Index(fields=['release', 'status'], name='edge_web_ap_release_92189e_idx')],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
