# Generated by Django 5.2.16 on 2026-08-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0006_alter_webapp_auto_promote_webappdeployment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webapp',
            name='auto_promote',
        ),
    ]
