# Generated by Django 5.2.4 on 2026-08-10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0049_bouncersignal_account_bou_ip_addr_e101ed_idx"),
        ("edge", "0007_remove_webapp_auto_promote"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAppKeyOperation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("operation_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("action", models.CharField(choices=[("mint", "Mint"), ("rotate", "Rotate"), ("revoke", "Revoke")], max_length=12)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="webapp_key_operations", to="account.user")),
                ("api_key", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="webapp_key_operations", to="account.apikey")),
                ("web_app", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="key_operations", to="edge.webapp")),
            ],
            options={
                "db_table": "edge_web_app_key_operation",
                "ordering": ["-created"],
                "constraints": [models.UniqueConstraint(fields=("web_app", "operation_id"), name="edge_webapp_key_operation_uniq")],
            },
        ),
    ]
