# Generated by Django 5.2.16 on 2026-08-10 18:07

import django.db.models.deletion
import mojo.models.rest
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_systemsetupoperation'),
        ('dnsman', '0004_dnsrecordreservation'),
        ('edge', '0008_webappkeyoperation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webapp',
            name='build_output',
            field=models.CharField(blank=True, default='dist', help_text='Validated relative build-output directory.', max_length=255),
        ),
        migrations.AddField(
            model_name='webapp',
            name='deployment_ref',
            field=models.CharField(blank=True, default='main', help_text='Validated branch or tag used by the generated workflow.', max_length=255),
        ),
        migrations.AddField(
            model_name='webapp',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Human-facing application name; never a storage or route key.', max_length=120),
        ),
        migrations.AddField(
            model_name='webapp',
            name='environment',
            field=models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('preview', 'Preview'), ('development', 'Development')], db_index=True, default='production', max_length=16),
        ),
        migrations.AddField(
            model_name='webapp',
            name='github_repository',
            field=models.CharField(blank=True, default='', help_text='Validated OWNER/REPOSITORY identifier; never a URL.', max_length=255),
        ),
        migrations.CreateModel(
            name='WebAppOnboardingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('waiting', 'Waiting for a choice or provider'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=16)),
                ('cursor', models.CharField(db_index=True, default='app', max_length=24)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('origin', models.CharField(max_length=255)),
                ('replay_fingerprint', models.CharField(max_length=64)),
                ('registrar_provider', models.CharField(blank=True, default='', max_length=32)),
                ('dns_provider', models.CharField(blank=True, default='', max_length=32)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('activity', models.JSONField(blank=True, default=list)),
                ('lease_owner', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('actor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webapp_onboarding_operations', to=settings.AUTH_USER_MODEL)),
                ('certificate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webapp_onboarding_operations', to='dnsman.certificate')),
                ('domain', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webapp_onboarding_operations', to='dnsman.domain')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webapp_onboarding_operations', to='account.group')),
                ('vhost', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webapp_onboarding_operations', to='edge.vhost')),
                ('web_app', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_operations', to='edge.webapp')),
            ],
            options={
                'db_table': 'edge_web_app_onboarding_operation',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['group', 'status', 'modified'], name='edge_web_ap_group_i_7096ec_idx'), models.Index(fields=['status', 'next_attempt_at'], name='edge_web_ap_status_bce361_idx'), models.Index(fields=['web_app', 'status'], name='edge_web_ap_web_app_851729_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('active', 'waiting'))), fields=('group', 'replay_fingerprint'), name='edge_webapp_onboarding_live_replay_uniq')],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
