# Generated by Django 5.2.16 on 2026-08-10 18:43

import django.db.models.deletion
import mojo.models.rest
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0009_webapp_onboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('started', models.DateTimeField(blank=True, default=None, null=True)),
                ('finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('sha', models.CharField(db_index=True, max_length=40)),
                ('framework_version', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(db_index=True, default='requested', max_length=20)),
                ('source', models.CharField(db_index=True, default='external', max_length=32)),
                ('actor', models.CharField(blank=True, default='', max_length=160)),
                ('request_key', models.CharField(max_length=128, unique=True)),
                ('source_delivery', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('frozen_roster', models.JSONField(blank=True, default=list)),
                ('transitions', models.JSONField(blank=True, default=list)),
                ('node_evidence', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=dict)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_deployments', to=settings.AUTH_USER_MODEL)),
                ('retry_of', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry_attempts', to='edge.platformdeployment')),
            ],
            options={
                'db_table': 'edge_platform_deployment',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['sha', '-created'], name='edge_platfo_sha_5af813_idx'), models.Index(fields=['status', '-created'], name='edge_platfo_status_411b5d_idx'), models.Index(fields=['source', 'source_delivery'], name='edge_platfo_source_a0eeba_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'github'), models.Q(('source_delivery', ''), _negated=True)), fields=('source', 'source_delivery'), name='edge_platform_unique_github_delivery')],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
