# Generated by Django 5.2.16 on 2026-08-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0010_platformdeployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vhost',
            name='mojosec_policy',
            field=models.JSONField(blank=True, default=dict, help_text='Versioned opt-in impossible-path and trusted response classification policy. Empty keeps legacy behavior.'),
        ),
    ]
