# Generated by Django 5.2.16 on 2026-08-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0011_vhost_mojosec_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformdeployment',
            name='diagnosis',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
