# Generated by Django 5.2.16 on 2026-08-20 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0012_platformdeployment_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='vhost',
            name='alias_of',
            field=models.ForeignKey(blank=True, default=None, help_text="Set when this vhost is an extra address for a WebApp; the app's primary address stays WebApp.vhost.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_vhosts', to='edge.webapp'),
        ),
    ]
