# Generated by Django 5.2.16 on 2026-08-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0013_vhost_alias_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapprelease',
            name='source',
            field=models.CharField(choices=[('github', 'Pushed by the GitHub Action'), ('api', 'Registered by a key-authenticated client'), ('upload', 'Uploaded from an interactive session'), ('unknown', 'Registered before arrival was recorded')], default='unknown', help_text='How the release FIRST arrived; re-registering the same version never restamps it.', max_length=16),
        ),
    ]
