# Generated by Django 5.2.16 on 2026-08-22 03:31

import django.db.models.deletion
import mojo.models.rest
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0014_webapprelease_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAppRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('path_prefix', models.CharField(help_text='Canonical custom request-path prefix, such as /api.', max_length=128)),
                ('upstream', models.ForeignKey(help_text='Declared destination retained while the app is offline.', on_delete=django.db.models.deletion.PROTECT, related_name='web_app_routes', to='edge.upstream')),
                ('web_app', models.ForeignKey(help_text='The app whose every serving address materializes this path.', on_delete=django.db.models.deletion.CASCADE, related_name='desired_routes', to='edge.webapp')),
            ],
            options={
                'db_table': 'edge_web_app_route',
                'ordering': ['web_app', 'path_prefix'],
                'constraints': [models.UniqueConstraint(fields=('web_app', 'path_prefix'), name='edge_webapp_route_app_prefix_uniq')],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
