# Generated by Django 5.2.16 on 2026-08-30 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='client_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_key__isnull', False)), fields=('room', 'user', 'client_key'), name='chat_message_client_key_uniq'),
        ),
    ]
