# Generated by Django 5.2.16 on 2026-08-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_client_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('system', 'System'), ('card', 'Card'), ('file', 'File')], default='text', max_length=20),
        ),
    ]
