# Generated by Django 5.2.16 on 2026-09-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='moderation_reasons',
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='moderation_score',
            field=models.PositiveSmallIntegerField(blank=True, db_default=None, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='moderation_decision',
            field=models.CharField(choices=[('allow', 'Allow'), ('warn', 'Warn'), ('masked', 'Masked'), ('block', 'Block')], default='allow', max_length=10),
        ),
    ]
