# Generated by Django 5.2.16 on 2026-07-28 16:24

import django.db.models.deletion
import mojo.models.rest
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docit', '0003_alter_book_group'),
    ]

    operations = [
        # CREATE EXTENSION IF NOT EXISTS vector — requires a role allowed to
        # create extensions; on managed Postgres (RDS/Aurora/Supabase) this
        # works as-is, otherwise create the extension manually first.
        VectorExtension(),
        migrations.CreateModel(
            name='PageChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(db_index=True, default=0, help_text='Order of the chunk within its page')),
                ('heading', models.CharField(blank=True, default='', help_text="Heading breadcrumb, e.g. 'Install > Quickstart'", max_length=300)),
                ('content', models.TextField(help_text='Raw markdown slice, including its heading line')),
                ('content_hash', models.CharField(db_index=True, help_text='sha256 of heading + content; unchanged chunks are never re-embedded', max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1024, help_text='Vector embedding; null until a provider fills it', null=True)),
                ('embed_model', models.CharField(blank=True, default='', help_text='Model id that produced the embedding', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('page', models.ForeignKey(help_text='Page this chunk was sliced from', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='docit.page')),
            ],
            options={
                'ordering': ['page', 'position'],
                'indexes': [pgvector.django.indexes.HnswIndex(fields=['embedding'], name='docit_kb_chunk_emb_hnsw', opclasses=['vector_cosine_ops'])],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
