# Generated by Django 5.2.16 on 2026-07-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docit_kb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagechunk',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True, help_text='Pipeline verification watermark — the page version these chunks were built from'),
        ),
    ]
