# Generated by Django 5.2.16 on 2026-07-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docit', '0003_alter_book_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, help_text='Opt this book into anonymous public reading via the /api/docit/public endpoints. Off by default — the authenticated endpoints stay tenant-scoped either way.'),
        ),
    ]
