# Generated by Django 5.2.12 on 2026-04-24 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0013_file_shortlink_code_filerendition_shortlink_code'),
        ('shortlink', '0002_shortlink_is_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='rendition',
            field=models.ForeignKey(blank=True, default=None, help_text='Optional linked rendition for rendition-sharing shortlinks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortlinks', to='fileman.filerendition'),
        ),
    ]
