# Generated by Django 5.2.12 on 2026-04-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0012_remove_filemanager_fileman_fil_group_i_c1c47d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='shortlink_code',
            field=models.CharField(blank=True, db_index=True, default=None, help_text="Code of the shortlink that wraps this file's download URL (tier 1, internal)", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='filerendition',
            name='shortlink_code',
            field=models.CharField(blank=True, db_index=True, default=None, help_text="Code of the shortlink that wraps this rendition's download URL (tier 1, internal)", max_length=10, null=True),
        ),
    ]
