# Generated by Django 5.2.16 on 2026-09-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0015_uploadinitiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerendition',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Bounded diagnostic for a failed rendition'),
        ),
    ]
