# Generated by Django 5.2.12 on 2026-04-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0025_alter_ruleset_retrigger_every_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
