# Generated by Django 5.2.12 on 2026-04-25 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_publicmessage'),
        ('incident', '0026_ruleset_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.group'),
        ),
        migrations.AddField(
            model_name='incident',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.group'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='bundle_by',
            field=models.IntegerField(choices=[(0, "Don't bundle - each event creates new incident"), (1, 'Bundle by hostname'), (2, 'Bundle by model type'), (3, 'Bundle by specific model instance'), (4, 'Bundle by source IP'), (5, 'Bundle by hostname + model type'), (6, 'Bundle by hostname + specific model'), (7, 'Bundle by IP + model type'), (8, 'Bundle by IP + specific model'), (9, 'Bundle by IP + hostname'), (10, 'Bundle by group'), (11, 'Bundle by group + model type'), (12, 'Bundle by group + specific model'), (13, 'Bundle by group + source IP')], default=3, help_text='How to group events into incidents'),
        ),
    ]
