# Generated by Django 5.2.12 on 2026-05-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0027_event_group_incident_group_alter_ruleset_bundle_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketnote',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
