# Generated by Django 5.2.12 on 2026-06-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0029_ticketnote_user_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source_ip',
            field=models.CharField(db_index=True, default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='source_ip',
            field=models.CharField(db_index=True, default=None, max_length=45, null=True),
        ),
    ]
