# Generated by Django 5.2.16 on 2026-07-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0030_alter_event_source_ip_alter_incident_source_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipset',
            name='source',
            field=models.CharField(choices=[('ipdeny', 'ipdeny.com'), ('abuseipdb', 'AbuseIPDB'), ('tor', 'Tor Exit List'), ('blocklist_de', 'blocklist.de'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
    ]
