# Generated by Django 5.2.16 on 2026-07-16 21:11

import django.db.models.deletion
import mojo.apps.incident.models.maestro_board
import mojo.models.rest
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_geolocatedip_whitelisted_until'),
        ('incident', '0031_alter_ipset_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaestroBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mojo_secrets', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('api_url', models.CharField(blank=True, default='', max_length=255)),
                ('remote_board_id', models.IntegerField(blank=True, default=None, null=True)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('status_map', models.JSONField(blank=True, default=None, null=True)),
                ('sync_notes', models.BooleanField(default=True)),
                ('callback_token', models.CharField(db_index=True, default=mojo.apps.incident.models.maestro_board.generate_callback_token, max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.group')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='MaestroBoardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('remote_item_id', models.IntegerField(db_index=True)),
                ('remote_url', models.CharField(blank=True, default='', max_length=500)),
                ('last_synced', models.DateTimeField(blank=True, default=None, null=True)),
                ('maestro_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='incident.maestroboard')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_links', to='incident.ticket')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('ticket', 'maestro_board')},
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
