# Generated by Django 5.2.16 on 2026-08-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_bouncersignal_account_bou_ip_addr_e101ed_idx'),
        ('incident', '0032_maestroboard_maestroboardlink'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['source_ip', 'created'], name='incident_ev_source__4ef806_idx'),
        ),
    ]
