# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incident", "0033_event_incident_ev_source__4ef806_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidenthistory",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="MaestroItemLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True, editable=False)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("remote_integration_id", models.CharField(db_index=True, max_length=100)),
                ("remote_item_id", models.BigIntegerField(db_index=True)),
                ("remote_board_id", models.BigIntegerField(blank=True, db_index=True, default=None, null=True)),
                ("remote_url", models.CharField(blank=True, default="", max_length=500)),
                ("last_synced", models.DateTimeField(blank=True, default=None, null=True)),
                ("incident", models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="maestro_links", to="incident.incident")),
                ("ticket", models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="maestro_links", to="incident.ticket")),
            ],
            options={
                "ordering": ["-created"],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(models.Q(("incident__isnull", True), ("ticket__isnull", False)), models.Q(("incident__isnull", False), ("ticket__isnull", True)), _connector="OR"), name="incident_maestro_link_one_source"),
                    models.UniqueConstraint(condition=models.Q(("ticket__isnull", False)), fields=("ticket",), name="incident_maestro_link_ticket_unique"),
                    models.UniqueConstraint(condition=models.Q(("incident__isnull", False)), fields=("incident",), name="incident_maestro_link_incident_unique"),
                    models.UniqueConstraint(fields=("remote_integration_id", "remote_item_id"), name="incident_maestro_link_remote_unique"),
                ],
            },
        ),
    ]
