# Generated by Django 5.2.16 on 2026-08-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileman', '0015_uploadinitiation'),
        ('incident', '0034_incidenthistory_metadata_maestroitemlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenthistory',
            name='media',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fileman.file'),
        ),
    ]
