# Generated by Django 5.2.16 on 2026-08-09 04:00

import django.db.models.deletion
import mojo.models.rest
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_bouncersignal_account_bou_ip_addr_e101ed_idx'),
        ('incident', '0035_alter_incidenthistory_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='MojoSecReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('sensor_id', models.CharField(db_index=True, max_length=128)),
                ('wire_event_id', models.CharField(max_length=64)),
                ('payload_digest', models.CharField(max_length=64)),
                ('protocol_version', models.PositiveSmallIntegerField(default=1)),
                ('sensor_policy_revision', models.CharField(blank=True, default='', max_length=128)),
                ('publish_state', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], db_index=True, default='pending', max_length=16)),
                ('publish_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=256)),
                ('replay_features', models.JSONField(blank=True, default=dict)),
                ('handler_state', models.CharField(choices=[('none', 'No handler'), ('pending', 'Pending'), ('queued', 'Queued'), ('dispatched', 'Dispatched'), ('failed', 'Failed')], db_index=True, default='none', max_length=16)),
                ('handler_attempts', models.PositiveIntegerField(default=0)),
                ('handler_job_id', models.CharField(blank=True, default='', max_length=32)),
                ('handler_last_error', models.CharField(blank=True, default='', max_length=256)),
                ('handler_dispatched_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mojosec_receipts', to='account.apikey')),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mojosec_receipts', to='incident.event')),
                ('incident', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incident.incident')),
                ('rule_set', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incident.ruleset')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['publish_state', 'modified'], name='incident_mo_publish_0ddfd1_idx')],
                'constraints': [models.UniqueConstraint(fields=('api_key', 'wire_event_id'), name='incident_mojosec_key_event_uniq')],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
