# Generated by Django 5.2.16 on 2026-08-09

import django.db.models.deletion
import mojo.models.rest
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0049_bouncersignal_account_bou_ip_addr_e101ed_idx"),
        ("incident", "0036_mojosecreceipt"),
    ]

    operations = [
        migrations.CreateModel(
            name="MojoSecPolicyProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("lineage_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("shadow", "Shadow"), ("rejected", "Rejected")], db_index=True, default="draft", max_length=16)),
                ("summary", models.CharField(blank=True, default="", max_length=500)),
                ("content", models.JSONField(default=dict)),
                ("content_digest", models.CharField(max_length=64)),
                ("row_digest", models.CharField(editable=False, max_length=64)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="account.user")),
                ("supersedes", models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="superseded_by", to="incident.mojosecpolicyproposal")),
            ],
            options={
                "ordering": ["-created"],
                "constraints": [models.UniqueConstraint(fields=("lineage_id", "revision"), name="incident_msp_lineage_revision_uniq")],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name="MojoSecPolicyEvaluation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("mode", models.CharField(choices=[("replay", "Replay"), ("shadow", "Shadow")], db_index=True, max_length=16)),
                ("sample_count", models.PositiveSmallIntegerField(default=0)),
                ("sample_digest", models.CharField(max_length=64)),
                ("result_digest", models.CharField(max_length=64)),
                ("metrics", models.JSONField(default=dict)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="account.user")),
                ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evaluations", to="incident.mojosecpolicyproposal")),
            ],
            options={"ordering": ["-created"]},
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name="MojoSecDetectorFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("disposition", models.CharField(choices=[("confirmed_threat", "Confirmed threat"), ("expected_administrative", "Expected administrative activity"), ("benign_noise", "Benign noise"), ("operational_failure", "Operational failure"), ("unknown", "Unknown"), ("missed_incomplete", "Missed or incomplete detection")], db_index=True, max_length=32)),
                ("note", models.CharField(blank=True, default="", max_length=1000)),
                ("subject_type", models.CharField(choices=[("receipt", "Receipt"), ("manual", "Manual")], db_index=True, max_length=16)),
                ("subject_key", models.CharField(db_index=True, max_length=160)),
                ("subject_id_snapshot", models.CharField(max_length=128)),
                ("manual_exemplar", models.JSONField(blank=True, default=dict)),
                ("author_id_snapshot", models.PositiveBigIntegerField()),
                ("author_identity_snapshot", models.CharField(max_length=254)),
                ("installation_key_id_snapshot", models.PositiveBigIntegerField(default=None, null=True)),
                ("receipt_wire_event_id_snapshot", models.CharField(blank=True, default="", max_length=64)),
                ("incident_id_snapshot", models.PositiveBigIntegerField(default=None, null=True)),
                ("detector_kind", models.CharField(db_index=True, max_length=64)),
                ("detector_category", models.CharField(blank=True, default="", max_length=124)),
                ("detector_level", models.PositiveSmallIntegerField(default=0)),
                ("sensor_id", models.CharField(blank=True, db_index=True, default="", max_length=128)),
                ("sensor_policy_revision_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("observed_count", models.PositiveIntegerField(default=1)),
                ("row_digest", models.CharField(editable=False, max_length=64)),
                ("author", models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="account.user")),
                ("incident", models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="mojosec_detector_feedback", to="incident.incident")),
                ("receipt", models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="detector_feedback", to="incident.mojosecreceipt")),
                ("reverses", models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reversed_by", to="incident.mojosecdetectorfeedback")),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [models.Index(fields=["detector_kind", "created"], name="incident_msf_kind_created_idx")],
                "constraints": [models.CheckConstraint(condition=models.Q(models.Q(("subject_type", "receipt"), ("manual_exemplar", {})), models.Q(("subject_type", "manual"), ("receipt__isnull", True), ("incident__isnull", True), models.Q(("manual_exemplar", {}), _negated=True)), _connector="OR"), name="incident_msf_exact_subject")],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name="MojoSecDetectorFeedbackHead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("subject_key", models.CharField(max_length=160, unique=True)),
                ("current", models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="current_subject_head", to="incident.mojosecdetectorfeedback")),
            ],
            options={"ordering": ["subject_key"]},
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
