# Generated by Django 5.2.16 on 2026-08-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0037_mojosecdetectorfeedback_mojosecpolicyproposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
