# Generated by Django 5.2.16 on 2026-08-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0038_alter_ticket_created_alter_ticket_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mojosecreceipt',
            name='handler_state',
            field=models.CharField(choices=[('none', 'No handler'), ('pending', 'Pending'), ('queued', 'Queued'), ('dispatched', 'Dispatched'), ('failed', 'Failed'), ('dead', 'Dead')], db_index=True, default='none', max_length=16),
        ),
        migrations.AlterField(
            model_name='mojosecreceipt',
            name='publish_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('dead', 'Dead')], db_index=True, default='pending', max_length=16),
        ),
    ]
