# Generated by Django 5.2.16 on 2026-08-18 02:45

import django.db.models.deletion
import mojo.models.rest
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_user_requires_password_change'),
        ('incident', '0039_alter_mojosecreceipt_handler_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MojoSecCaseTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('receipt_id_snapshot', models.PositiveBigIntegerField()),
                ('transition', models.CharField(db_index=True, max_length=32)),
                ('reason', models.CharField(max_length=96)),
                ('from_state', models.CharField(blank=True, default='', max_length=16)),
                ('to_state', models.CharField(max_length=16)),
                ('from_urgency', models.CharField(blank=True, default='', max_length=16)),
                ('to_urgency', models.CharField(max_length=16)),
                ('occurrence_count', models.PositiveBigIntegerField()),
                ('receipt_count', models.PositiveBigIntegerField()),
                ('projected_event_count', models.PositiveBigIntegerField()),
                ('distinct_count', models.PositiveBigIntegerField()),
                ('sample_count', models.PositiveSmallIntegerField()),
                ('overflow_count', models.PositiveBigIntegerField()),
                ('policy_version', models.PositiveIntegerField()),
                ('evaluator_version', models.PositiveIntegerField()),
                ('row_digest', models.CharField(editable=False, max_length=64)),
            ],
            options={
                'ordering': ['created', 'id'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.AddField(
            model_name='mojosecreceipt',
            name='case_contributed_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mojosecreceipt',
            name='case_sample_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='MojoSecCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_seen', models.DateTimeField(db_index=True)),
                ('last_seen', models.DateTimeField(db_index=True)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField(db_index=True)),
                ('sensor_id', models.CharField(db_index=True, max_length=128)),
                ('sensor_kind', models.CharField(db_index=True, max_length=16)),
                ('resource_id', models.CharField(blank=True, db_index=True, default='', max_length=96)),
                ('family', models.CharField(db_index=True, max_length=64)),
                ('network', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('correlation_key', models.CharField(max_length=64)),
                ('window_key', models.CharField(max_length=64)),
                ('policy_version', models.PositiveIntegerField(default=1)),
                ('evaluator_version', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('observing', 'Observing'), ('elevated', 'Elevated')], db_index=True, default='observing', max_length=16)),
                ('state_reason', models.CharField(default='shadow_observation', max_length=96)),
                ('urgency', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', max_length=16)),
                ('urgency_reason', models.CharField(default='unknown_evidence', max_length=96)),
                ('occurrence_count', models.PositiveBigIntegerField(default=0)),
                ('receipt_count', models.PositiveBigIntegerField(default=0)),
                ('projected_event_count', models.PositiveBigIntegerField(default=0)),
                ('distinct_count', models.PositiveBigIntegerField(default=0)),
                ('sample_count', models.PositiveSmallIntegerField(default=0)),
                ('overflow_count', models.PositiveBigIntegerField(default=0)),
                ('samples', models.JSONField(blank=True, default=list)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mojosec_cases', to='account.group')),
                ('installation_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mojosec_cases', to='account.apikey')),
            ],
            options={
                'ordering': ['-last_seen', '-id'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.AddField(
            model_name='mojosecreceipt',
            name='mojosec_case',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='incident.mojoseccase'),
        ),
        migrations.AddIndex(
            model_name='mojosecreceipt',
            index=models.Index(fields=['mojosec_case', 'case_sample_key'], name='incident_mo_case_sample_idx'),
        ),
        migrations.AddField(
            model_name='mojoseccasetransition',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='incident.mojoseccase'),
        ),
        migrations.AddField(
            model_name='mojoseccasetransition',
            name='receipt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_transitions', to='incident.mojosecreceipt'),
        ),
        migrations.AddIndex(
            model_name='mojoseccase',
            index=models.Index(fields=['state', 'urgency', '-last_seen'], name='incident_msc_state_urg_idx'),
        ),
        migrations.AddIndex(
            model_name='mojoseccase',
            index=models.Index(fields=['installation_key', 'sensor_kind', '-last_seen'], name='incident_msc_install_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='mojoseccase',
            index=models.Index(fields=['resource_id', '-last_seen'], name='incident_msc_resource_idx'),
        ),
        migrations.AddConstraint(
            model_name='mojoseccase',
            constraint=models.UniqueConstraint(fields=('installation_key', 'correlation_key', 'window_key'), name='incident_msc_window_uniq'),
        ),
        migrations.AddIndex(
            model_name='mojoseccasetransition',
            index=models.Index(fields=['case', 'created'], name='incident_msct_case_idx'),
        ),
        migrations.AddConstraint(
            model_name='mojoseccasetransition',
            constraint=models.UniqueConstraint(fields=('receipt_id_snapshot',), name='incident_msct_receipt_uniq'),
        ),
    ]
