# Generated by Django 5.2.16 on 2026-08-21 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0040_mojoseccasetransition_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mojoseccasetransition',
            name='incident_msct_receipt_uniq',
        ),
        migrations.AddField(
            model_name='mojoseccase',
            name='breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mojoseccase',
            name='deployment_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='mojoseccase',
            name='projected_urgency',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='mojoseccase',
            name='projection_dispatched_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mojoseccase',
            name='settled_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='mojoseccasetransition',
            name='projected_event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incident.event'),
        ),
        migrations.AddField(
            model_name='mojoseccasetransition',
            name='projected_event_id_snapshot',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mojosecreceipt',
            name='case_routed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='mojoseccase',
            name='state',
            field=models.CharField(choices=[('observing', 'Observing'), ('elevated', 'Elevated'), ('settled', 'Settled')], db_index=True, default='observing', max_length=16),
        ),
        migrations.AlterField(
            model_name='mojoseccasetransition',
            name='receipt_id_snapshot',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='mojoseccasetransition',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_id_snapshot__gt', 0)), fields=('receipt_id_snapshot',), name='incident_msct_receipt_uniq'),
        ),
    ]
