# Generated by Django 5.2.16 on 2026-08-21 14:18

import django.db.models.deletion
import mojo.models.rest
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_user_requires_password_change'),
        ('incident', '0041_remove_mojoseccasetransition_incident_msct_receipt_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MojoSecDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('deployment_id', models.CharField(db_index=True, max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('note', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'ordering': ['-created', '-id'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='MojoSecExecutionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('attempt_number', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('outcome', models.CharField(choices=[('applied', 'Applied'), ('pre_existing', 'Pre-existing'), ('whitelisted', 'Whitelisted'), ('failed', 'Failed'), ('reverse_applied', 'Reverse applied'), ('reverse_failed', 'Reverse failed'), ('expire_confirmed', 'Expire confirmed')], db_index=True, max_length=20)),
                ('detail', models.CharField(blank=True, default='', max_length=256)),
                ('row_digest', models.CharField(editable=False, max_length=64)),
            ],
            options={
                'ordering': ['created', 'id'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='MojoSecRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('action', models.CharField(choices=[('temporary_block_ip', 'Temporary IP block'), ('temporary_block_ip_set', 'Temporary IP set block')], db_index=True, max_length=32)),
                ('state', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('auto_approved', 'Auto-approved'), ('executing', 'Executing'), ('executed', 'Executed'), ('failed', 'Failed'), ('expired', 'Expired'), ('reversed', 'Reversed'), ('rejected', 'Rejected')], db_index=True, default='proposed', max_length=16)),
                ('reason_code', models.CharField(max_length=96)),
                ('explanation', models.CharField(blank=True, default='', max_length=512)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8)),
                ('urgency', models.CharField(max_length=16)),
                ('requested_scope', models.CharField(choices=[('installation', 'Installation'), ('group', 'Group')], default='installation', max_length=16)),
                ('requested_ttl_seconds', models.PositiveIntegerField()),
                ('policy_version', models.PositiveIntegerField(default=1)),
                ('evaluator_version', models.PositiveIntegerField(default=1)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('approval_note', models.CharField(blank=True, default='', max_length=256)),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('validated_count', models.PositiveIntegerField(default=0)),
                ('protected_count', models.PositiveIntegerField(default=0)),
                ('executed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('reversed_count', models.PositiveIntegerField(default=0)),
                ('execution_rounds', models.PositiveIntegerField(default=0)),
                ('collateral', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'ordering': ['-created', '-id'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='MojoSecRecommendationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('ip', models.CharField(db_index=True, max_length=45)),
                ('kind', models.CharField(default='ip', max_length=8)),
                ('validation_state', models.CharField(choices=[('validated', 'Validated'), ('protected', 'Protected'), ('invalid', 'Invalid')], db_index=True, max_length=16)),
                ('validation_reason', models.CharField(blank=True, default='', max_length=96)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('pre_existing', 'Pre-existing'), ('whitelisted', 'Whitelisted'), ('failed', 'Failed'), ('expired', 'Expired'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=256)),
                ('applied_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('expires_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('prior_blocked_until', models.DateTimeField(blank=True, default=None, null=True)),
                ('prior_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='MojoSecRecommendationTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('transition', models.CharField(db_index=True, max_length=32)),
                ('reason', models.CharField(max_length=96)),
                ('from_state', models.CharField(blank=True, default='', max_length=16)),
                ('to_state', models.CharField(max_length=16)),
                ('actor_id_snapshot', models.PositiveBigIntegerField(default=0)),
                ('target_count', models.PositiveIntegerField()),
                ('validated_count', models.PositiveIntegerField()),
                ('protected_count', models.PositiveIntegerField()),
                ('executed_count', models.PositiveIntegerField()),
                ('failed_count', models.PositiveIntegerField()),
                ('reversed_count', models.PositiveIntegerField()),
                ('row_digest', models.CharField(editable=False, max_length=64)),
            ],
            options={
                'ordering': ['created', 'id'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.AddField(
            model_name='mojoseccase',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='incident.mojoseccase'),
        ),
        migrations.AddField(
            model_name='mojoseccase',
            name='distinct_source_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mojoseccase',
            name='observed_sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='mojoseccase',
            index=models.Index(fields=['installation_key', 'sensor_id', '-last_seen'], name='incident_msc_inst_sensor_idx'),
        ),
        migrations.AddConstraint(
            model_name='mojoseccase',
            constraint=models.UniqueConstraint(condition=models.Q(('sensor_kind', 'campaign')), fields=('correlation_key', 'window_key'), name='incident_msc_campaign_uniq'),
        ),
        migrations.AddField(
            model_name='mojosecdeployment',
            name='installation_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mojosec_deployments', to='account.apikey'),
        ),
        migrations.AddField(
            model_name='mojosecdeployment',
            name='registered_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mojosecrecommendation',
            name='approved_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mojosecrecommendation',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='incident.mojoseccase'),
        ),
        migrations.AddField(
            model_name='mojosecrecommendation',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mojosec_recommendations', to='account.group'),
        ),
        migrations.AddField(
            model_name='mojosecrecommendation',
            name='installation_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mojosec_recommendations', to='account.apikey'),
        ),
        migrations.AddField(
            model_name='mojosecexecutionattempt',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='incident.mojosecrecommendation'),
        ),
        migrations.AddField(
            model_name='mojosecrecommendationtarget',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='incident.mojosecrecommendation'),
        ),
        migrations.AddField(
            model_name='mojosecexecutionattempt',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_attempts', to='incident.mojosecrecommendationtarget'),
        ),
        migrations.AddField(
            model_name='mojosecrecommendationtransition',
            name='actor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mojosecrecommendationtransition',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='incident.mojosecrecommendation'),
        ),
        migrations.AddConstraint(
            model_name='mojosecdeployment',
            constraint=models.UniqueConstraint(fields=('installation_key', 'deployment_id'), name='incident_msd_key_deploy_uniq'),
        ),
        migrations.AddIndex(
            model_name='mojosecrecommendation',
            index=models.Index(fields=['state', '-created'], name='incident_msr_state_idx'),
        ),
        migrations.AddIndex(
            model_name='mojosecrecommendation',
            index=models.Index(fields=['installation_key', '-created'], name='incident_msr_install_idx'),
        ),
        migrations.AddConstraint(
            model_name='mojosecrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('proposed', 'approved', 'auto_approved', 'executing'))), fields=('case', 'action'), name='incident_msr_open_uniq'),
        ),
        migrations.AddIndex(
            model_name='mojosecrecommendationtarget',
            index=models.Index(fields=['outcome', 'expires_at'], name='incident_msrt_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='mojosecrecommendationtarget',
            constraint=models.UniqueConstraint(fields=('recommendation', 'ip'), name='incident_msrt_rec_ip_uniq'),
        ),
        migrations.AddIndex(
            model_name='mojosecexecutionattempt',
            index=models.Index(fields=['recommendation', 'created'], name='incident_msea_rec_idx'),
        ),
        migrations.AddIndex(
            model_name='mojosecrecommendationtransition',
            index=models.Index(fields=['recommendation', 'created'], name='incident_msrx_rec_idx'),
        ),
    ]
