# Generated by Django 5.2.12 on 2026-05-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonehub', '0002_phonenumber_region_phonenumber_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneconfig',
            name='mojo_remote_url',
            field=models.CharField(blank=True, help_text='Base URL of the remote django-mojo instance, e.g. https://sms.example.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phoneconfig',
            name='provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('aws', 'AWS SNS'), ('mojo', 'Mojo Remote Instance')], db_index=True, default='twilio', max_length=20),
        ),
        migrations.AlterField(
            model_name='sms',
            name='provider',
            field=models.CharField(blank=True, help_text='twilio, aws, or mojo', max_length=20, null=True),
        ),
    ]
