# Generated by Django 5.2.12 on 2026-04-05 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_userloginevent'),
        ('assistant', '0002_message_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_conversations', to='account.group'),
        ),
    ]
