# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_conversation_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='duration_ms',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
