# Generated by Django 5.2.12 on 2026-04-07 08:24

import django.db.models.deletion
import mojo.models.rest
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_userloginevent'),
        ('assistant', '0004_message_duration_ms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('global', 'Global'), ('user', 'User'), ('group', 'Group')], db_index=True, max_length=8)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('triggers', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(default=list)),
                ('auto_execute', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_skills', to='account.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified'],
                'constraints': [models.UniqueConstraint(fields=('tier', 'user', 'group', 'name'), name='unique_skill_per_scope')],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
