# Generated by Django 5.2.12 on 2026-05-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='usage',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
