# Generated by Django 5.2.16 on 2026-08-21 20:19

import django.db.models.deletion
import mojo.models.rest
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_user_requires_password_change'),
        ('assistant', '0006_message_usage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tool_name', models.CharField(db_index=True, max_length=128)),
                ('permission', models.CharField(blank=True, default='', max_length=128)),
                ('args', models.JSONField(default=dict)),
                ('args_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('summary', models.TextField(blank=True, default='')),
                ('preview', models.JSONField(blank=True, default=None, null=True)),
                ('fresh_auth_seconds', models.IntegerField(blank=True, default=None, null=True)),
                ('requires_superuser', models.BooleanField(default=False)),
                ('requires_managed_infrastructure', models.BooleanField(default=False)),
                ('revision', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('result', models.JSONField(blank=True, default=None, null=True)),
                ('failure_code', models.CharField(blank=True, default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='assistant.conversation')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_pending_actions', to='account.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_pending_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['conversation', 'state'], name='assistant_p_convers_8d8c5e_idx'), models.Index(fields=['conversation', 'tool_name', 'args_fingerprint'], name='assistant_p_convers_ea5fec_idx')],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
