# Generated by Django 5.2.12 on 2026-04-06 20:38

import django.db.models.deletion
import mojo.models.rest
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_broadcast_alter_job_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable label', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description')),
                ('enabled', models.BooleanField(db_index=True, default=True, help_text='Whether this task is active')),
                ('run_once', models.BooleanField(default=False, help_text='Auto-disable after first execution')),
                ('task_type', models.CharField(choices=[('job', 'Job'), ('webhook', 'Webhook'), ('llm', 'LLM')], help_text='Type of task to execute', max_length=16)),
                ('run_times', models.JSONField(default=list, help_text='List of "HH:MM" strings, max 2 (e.g. ["09:00", "17:00"])')),
                ('run_days', models.JSONField(default=list, help_text='List of weekday ints 0-6 (Mon=0). Empty = every day (Mon-Sun)')),
                ('job_config', models.JSONField(default=dict, help_text='Type-specific config: job={func, payload}, webhook={url, data}, llm={system_prompt, user_prompt}')),
                ('notify', models.JSONField(default=list, help_text='Opt-in notification channels: ["email", "in_app", "sms", "push"]')),
                ('channel', models.CharField(default='default', help_text='Job channel for published jobs', max_length=100)),
                ('max_retries', models.IntegerField(default=0, help_text='Max retries for published jobs')),
                ('last_run', models.DateTimeField(blank=True, help_text='When this task last ran', null=True)),
                ('run_count', models.IntegerField(default=0, help_text='Total number of executions')),
                ('last_error', models.TextField(blank=True, default='', help_text='Last execution error')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(help_text='User who owns this task', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_scheduledtask',
                'ordering': ['-created'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], help_text='Execution result status', max_length=16)),
                ('output', models.TextField(blank=True, default='', help_text='Result content (LLM response, webhook status, etc.)')),
                ('error', models.TextField(blank=True, default='', help_text='Error message if failed')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(blank=True, help_text='The job that produced this result', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_results', to='jobs.job')),
                ('task', models.ForeignKey(help_text='The scheduled task that produced this result', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='jobs.scheduledtask')),
                ('user', models.ForeignKey(help_text='User who owns this result (denormalized from task)', on_delete=django.db.models.deletion.CASCADE, related_name='task_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_taskresult',
                'ordering': ['-created'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['enabled', '-created'], name='jobs_schedu_enabled_5a2a94_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['user', '-created'], name='jobs_schedu_user_id_e5915b_idx'),
        ),
        migrations.AddIndex(
            model_name='taskresult',
            index=models.Index(fields=['task', '-created'], name='jobs_taskre_task_id_933ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='taskresult',
            index=models.Index(fields=['user', '-created'], name='jobs_taskre_user_id_f57afb_idx'),
        ),
    ]
