# Generated by Django 5.2.12 on 2026-03-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0006_alter_emaildomain_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildomain',
            name='region',
            field=models.CharField(default='us-east-1', help_text='AWS region for SES operations', max_length=64),
        ),
    ]
