# Generated by Django 5.2.16 on 2026-08-04 03:50

import django.db.models.deletion
import mojo.models.rest
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0009_fix_region_dynamic_default'),
        ('incident', '0034_incidenthistory_metadata_maestroitemlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudWatchAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('alarm_key', models.CharField(max_length=64, unique=True)),
                ('alarm_arn', models.TextField()),
                ('current_state', models.CharField(blank=True, default='', max_length=32)),
                ('last_state_change', models.DateTimeField(blank=True, default=None, null=True)),
                ('active_incident', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incident.incident')),
            ],
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='CloudWatchAlarmTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('topic_arn', models.TextField()),
                ('sns_message_id', models.CharField(max_length=100)),
                ('old_state', models.CharField(max_length=32)),
                ('new_state', models.CharField(max_length=32)),
                ('state_changed_at', models.DateTimeField(db_index=True)),
                ('dispatch_status', models.CharField(db_index=True, default='complete', max_length=16)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='aws.cloudwatchalarm')),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incident.event')),
                ('incident', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incident.incident')),
            ],
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.AddField(
            model_name='cloudwatchalarm',
            name='opening_transition',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='aws.cloudwatchalarmtransition'),
        ),
        migrations.AddConstraint(
            model_name='cloudwatchalarmtransition',
            constraint=models.UniqueConstraint(fields=('topic_arn', 'sns_message_id'), name='aws_cw_topic_message_unique'),
        ),
        migrations.AddConstraint(
            model_name='cloudwatchalarmtransition',
            constraint=models.UniqueConstraint(fields=('alarm', 'state_changed_at', 'old_state', 'new_state'), name='aws_cw_logical_transition_unique'),
        ),
    ]
