# Generated by Django 5.2.16 on 2026-08-06 19:18

import django.db.models.deletion
import mojo.models.rest
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0010_cloudwatchalarm_cloudwatchalarmtransition_and_more'),
        ('incident', '0034_incidenthistory_metadata_maestroitemlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardDutyFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('finding_key', models.CharField(max_length=64, unique=True)),
                ('finding_id', models.CharField(blank=True, default='', max_length=128)),
                ('detector_id', models.CharField(blank=True, default='', max_length=64)),
                ('account', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('region', models.CharField(blank=True, default='', max_length=64)),
                ('finding_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('severity', models.FloatField(default=0.0)),
                ('level', models.IntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('occurrence_count', models.IntegerField(default=0)),
                ('dispatch_status', models.CharField(db_index=True, default='complete', max_length=16)),
                ('active_incident', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incident.incident')),
                ('opening_event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incident.event')),
                ('pending_event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='incident.event')),
            ],
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
