# Generated by Django 5.2.16 on 2026-08-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0011_guarddutyfinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudwatchalarmtransition',
            name='is_delivery_probe',
            field=models.BooleanField(db_index=True, default=False, help_text='Evidence-only System Setup probe; never dispatched to incident rules'),
        ),
    ]
