# Generated by Django 5.2.16 on 2026-07-25 23:26

import django.db.models.deletion
import mojo.models.rest
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0047_userloginevent_region_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcmeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mojo_secrets', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('directory_url', models.CharField(db_index=True, help_text='ACME directory URL. Distinguishes staging from production.', max_length=512, unique=True)),
                ('contact_email', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('account_url', models.CharField(blank=True, default=None, help_text="The CA's account URL, used as the JWS 'kid' for every later request.", max_length=512, null=True)),
                ('status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('last_error', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'dnsman_acme_account',
                'ordering': ['directory_url'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='DnsCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mojo_secrets', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text="Human label for this credential, e.g. 'Acme Corp GoDaddy'.", max_length=200)),
                ('provider', models.CharField(db_index=True, default='godaddy', help_text='DNS provider this credential authenticates against: godaddy.', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Set False to retire a credential without deleting its history.')),
                ('verified', models.BooleanField(db_index=True, default=False, help_text='True once the provider API confirmed the key/secret works.')),
                ('verified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('domain_count', models.IntegerField(default=0, help_text='How many domains the provider account held at verification time. A health signal only — the domain list itself is never stored or exposed.')),
                ('last_error', models.TextField(blank=True, default=None, null=True)),
                ('group', models.ForeignKey(blank=True, default=None, help_text='Owning group. Null means a house/platform credential.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dns_credentials', to='account.group')),
            ],
            options={
                'db_table': 'dnsman_credential',
                'ordering': ['name'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, help_text='Normalized domain name: lowercase, IDNA-encoded, no trailing dot.', max_length=253, unique=True)),
                ('provider', models.CharField(db_index=True, default='route53', help_text="Where this domain's DNS lives: route53 | godaddy.", max_length=32)),
                ('status', models.CharField(db_index=True, default='pending', help_text='pending | registering | active | failed', max_length=32)),
                ('hosted_zone_id', models.CharField(blank=True, default=None, help_text='Route53 hosted zone id. Null for non-route53 providers.', max_length=128, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('privacy', models.BooleanField(default=True, help_text='WHOIS privacy. Not offered by every TLD — see route53.TLDS_WITHOUT_PRIVACY.')),
                ('verified', models.BooleanField(default=False, help_text='Ownership confirmed. Always true for domains we registered or adopted; set by the provider API probe for BYO domains.')),
                ('registered_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('expires', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('last_error', models.TextField(blank=True, default=None, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('credential', models.ForeignKey(blank=True, default=None, help_text='Required for providers we do not hold house credentials for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='dnsman.dnscredential')),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dns_domains', to='account.group')),
                ('user', models.ForeignKey(blank=True, default=None, help_text='Who brought this domain into the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dns_domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dnsman_domain',
                'ordering': ['name'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mojo_secrets', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('common_name', models.CharField(db_index=True, max_length=253)),
                ('sans', models.JSONField(blank=True, default=list, help_text='Every name on the certificate, including wildcards.')),
                ('status', models.CharField(db_index=True, default='pending', help_text='pending | issuing | active | failed | revoked', max_length=32)),
                ('issuer', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('serial', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('not_before', models.DateTimeField(blank=True, default=None, null=True)),
                ('not_after', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('renew_after', models.DateTimeField(blank=True, db_index=True, default=None, help_text='When the renewal scan should pick this up.', null=True)),
                ('cert_pem', models.TextField(blank=True, default=None, null=True)),
                ('chain_pem', models.TextField(blank=True, default=None, null=True)),
                ('acme_order_url', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('last_error', models.TextField(blank=True, default=None, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='dnsman.domain')),
            ],
            options={
                'db_table': 'dnsman_certificate',
                'ordering': ['-created'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='DomainPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('domain_name', models.CharField(db_index=True, max_length=253)),
                ('kind', models.CharField(default='register', max_length=32)),
                ('status', models.CharField(db_index=True, default='quoted', help_text='quoted | submitted | completed | failed | expired', max_length=32)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='What the registry quoted.', max_digits=9, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Our core cost. Equal to price today; a separate column so attribution/margin can diverge later without a migration.', max_digits=9, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('years', models.IntegerField(default=1)),
                ('confirm_token', models.CharField(blank=True, default=None, help_text='SHA-256 hash of the confirm token. The raw token is returned exactly once, in the quote response, and never stored.', max_length=128, null=True)),
                ('quote_expires', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('operation_id', models.CharField(blank=True, db_index=True, default=None, help_text='Registrar operation id. Absent on a submitted row means the crash window — the poller reconciles it via list_operations.', max_length=128, null=True)),
                ('error', models.TextField(blank=True, default=None, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_purchases', to='account.group')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dnsman_domain_purchase',
                'ordering': ['-created'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.AddIndex(
            model_name='dnscredential',
            index=models.Index(fields=['group', 'provider'], name='dnsman_cred_group_i_7be239_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['group', 'status'], name='dnsman_doma_group_i_3572c7_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['provider', 'status'], name='dnsman_doma_provide_eb9aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status', 'renew_after'], name='dnsman_cert_status_c891a2_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['domain', 'status'], name='dnsman_cert_domain__6f52b0_idx'),
        ),
        migrations.AddIndex(
            model_name='domainpurchase',
            index=models.Index(fields=['group', 'status'], name='dnsman_doma_group_i_147eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='domainpurchase',
            index=models.Index(fields=['status', 'created'], name='dnsman_doma_status_8e56b0_idx'),
        ),
    ]
