# Generated by Django 5.2.16 on 2026-08-06 16:13

import django.db.models.deletion
import mojo.models.rest
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_bouncersignal_account_bou_ip_addr_e101ed_idx'),
        ('dnsman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcmeHubDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('owner_project_uuid', models.CharField(db_index=True, max_length=200)),
                ('client_ref', models.CharField(max_length=128)),
                ('domain_name', models.CharField(db_index=True, max_length=253)),
                ('source_name', models.CharField(db_index=True, max_length=253)),
                ('target_name', models.CharField(max_length=253, unique=True)),
                ('allocation_zone_name', models.CharField(max_length=253)),
                ('allocation_zone_id', models.CharField(max_length=128)),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acme_hub_delegations', to='account.group')),
            ],
            options={
                'db_table': 'dnsman_acme_hub_delegation',
                'ordering': ['created'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='AcmeHubChallengeLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('challenge_ref', models.CharField(max_length=128)),
                ('record_values', models.JSONField(default=list)),
                ('state', models.CharField(db_index=True, default='pending', max_length=24)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('reconciled_at', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('last_error', models.TextField(blank=True, default=None, null=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenge_leases', to='dnsman.acmehubdelegation')),
            ],
            options={
                'db_table': 'dnsman_acme_hub_challenge_lease',
                'ordering': ['created'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.AddIndex(
            model_name='acmehubdelegation',
            index=models.Index(fields=['owner_project_uuid', 'domain_name'], name='dnsman_acme_owner_p_9b69a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='acmehubdelegation',
            constraint=models.UniqueConstraint(fields=('owner_project_uuid', 'client_ref'), name='dnsman_acme_hub_owner_client_uniq'),
        ),
        migrations.AddIndex(
            model_name='acmehubchallengelease',
            index=models.Index(fields=['allocation', 'state'], name='dnsman_acme_allocat_1c7ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='acmehubchallengelease',
            index=models.Index(fields=['state', 'expires_at'], name='dnsman_acme_state_2ca75c_idx'),
        ),
        migrations.AddIndex(
            model_name='acmehubchallengelease',
            index=models.Index(fields=['allocation', 'reconciled_at'], name='dnsman_acme_allocat_157405_idx'),
        ),
        migrations.AddConstraint(
            model_name='acmehubchallengelease',
            constraint=models.UniqueConstraint(fields=('allocation', 'challenge_ref'), name='dnsman_acme_hub_alloc_challenge_uniq'),
        ),
    ]
