# Generated by Django 5.2.16 on 2026-08-06 16:43

import django.db.models.deletion
import mojo.models.rest
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_bouncersignal_account_bou_ip_addr_e101ed_idx'),
        ('dnsman', '0002_acmehubdelegation_acmehubchallengelease_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='provider',
            field=models.CharField(db_index=True, default='route53', help_text="Where this domain's DNS lives: route53 | godaddy | mojo. mojo is certificate-only delegated ACME, never general DNS CRUD.", max_length=32),
        ),
        migrations.CreateModel(
            name='AcmeDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('tenant_uuid', models.CharField(db_index=True, max_length=200)),
                ('tenant_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('domain_name', models.CharField(db_index=True, max_length=253)),
                ('client_ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_name', models.CharField(blank=True, default=None, max_length=253, null=True)),
                ('target_name', models.CharField(blank=True, default=None, max_length=253, null=True, unique=True)),
                ('state', models.CharField(db_index=True, default='pending', max_length=24)),
                ('verified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('retired_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_error_code', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('cleanup_challenge_ref', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('cleanup_requested_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('domain', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acme_delegations', to='dnsman.domain')),
                ('group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acme_delegations', to='account.group')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acme_delegations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dnsman_acme_delegation',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['tenant_uuid', 'state'], name='dnsman_acme_tenant__4916e1_idx'), models.Index(fields=['domain', 'state'], name='dnsman_acme_domain__107fc5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'retired'), _negated=True), fields=('tenant_uuid', 'domain_name'), name='dnsman_acme_tenant_domain_live_uniq')],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
