# Generated by Django 5.2.16 on 2026-08-09

import django.db.models.deletion
import mojo.models.rest
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dnsman", "0003_alter_domain_provider_acmedelegation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DnsRecordReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(auto_now=True, db_index=True)),
                ("owner_ref", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("record_type", models.CharField(max_length=16)),
                ("record_name", models.CharField(max_length=253)),
                ("record_values", models.JSONField(blank=True, default=list)),
                ("state", models.CharField(db_index=True, default="reserved", max_length=24)),
                ("mutation_attempted", models.BooleanField(default=False)),
                ("mutation_proven", models.BooleanField(default=False)),
                ("last_error", models.TextField(blank=True, default=None, null=True)),
                ("certificate", models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="record_reservations", to="dnsman.certificate")),
                ("domain", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="record_reservations", to="dnsman.domain")),
            ],
            options={
                "db_table": "dnsman_record_reservation",
                "ordering": ["record_name", "record_type"],
                "indexes": [models.Index(fields=["domain", "state"], name="dnsman_reco_domain__0436d2_idx"), models.Index(fields=["certificate", "state"], name="dnsman_reco_certifi_ddac72_idx")],
                "constraints": [models.UniqueConstraint(condition=models.Q(("state__in", ("reserved", "cleanup_pending"))), fields=("domain", "record_type", "record_name"), name="dnsman_record_reservation_live_uniq")],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
