# Generated by Django 5.2.7 on 2026-02-24 15:39

import django.db.models.deletion
import mojo.models.rest
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_passkeychallenge_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mojo_secrets', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('token_hash', models.CharField(db_index=True, default=None, max_length=64, null=True, unique=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('last_used', models.DateTimeField(default=None, null=True)),
                ('expires_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='account.group')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
