# Generated by Django 5.2.12 on 2026-04-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_userloginevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='auth_domain',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
