# Generated by Django 5.2.12 on 2026-05-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_disable_lifecycle_migrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocatedip',
            name='region_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
