# Generated by Django 5.2.12 on 2026-06-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_webhooksubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouncersignal',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='geolocatedip',
            name='subnet',
            field=models.CharField(db_index=True, default=None, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='userloginevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
