# Generated by Django 5.2.12 on 2026-07-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_alter_bouncersignal_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocatedip',
            name='whitelisted_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the whitelist expires (null = permanent)', null=True),
        ),
    ]
