# Generated by Django 5.2.16 on 2026-07-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_geolocatedip_whitelisted_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginevent',
            name='region_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
