# Generated by Django 5.2.16 on 2026-07-27 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_userloginevent_region_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='override_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
