# Generated by Django 5.2.16 on 2026-08-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_apikey_override_user_apikey_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bouncersignal',
            index=models.Index(fields=['ip_address', 'created'], name='account_bou_ip_addr_e101ed_idx'),
        ),
    ]
