# Generated by Django 5.2.16 on 2026-08-10 03:32

import django.db.models.deletion
import mojo.models.rest
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_bouncersignal_account_bou_ip_addr_e101ed_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetupOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('mode', models.CharField(choices=[('check', 'Check'), ('fix', 'Fix')], db_index=True, max_length=16)),
                ('section', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('waiting_for_choice', 'Waiting For Choice'), ('reconciling', 'Reconciling'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=32)),
                ('replay_fingerprint', models.CharField(max_length=64, unique=True)),
                ('bound_origin', models.CharField(max_length=255)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('steps', models.JSONField(default=list)),
                ('choices', models.JSONField(default=dict)),
                ('report', models.JSONField(default=dict)),
                ('operation_log', models.JSONField(default=list)),
                ('lease_owner', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_setup_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mode', 'fix'), ('status__in', ('planned', 'running', 'waiting_for_choice', 'reconciling'))), fields=('mode',), name='account_one_active_system_fix')],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
