# Generated by Django 5.2.16 on 2026-08-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_systemsetupoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_password_change',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
