# Generated by Django 5.2.16 on 2026-08-22 06:06

import django.db.models.deletion
import mojo.models.rest
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_user_requires_password_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('client_id', models.CharField(db_index=True, max_length=512, unique=True)),
                ('kind', models.CharField(default='dcr', max_length=16)),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('redirect_uris', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_used', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='OAuthGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('access_jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('access_expires', models.DateTimeField(default=None, null=True)),
                ('refresh_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('prev_refresh_hash', models.CharField(db_index=True, default=None, max_length=64, null=True)),
                ('refresh_expires', models.DateTimeField(db_index=True)),
                ('last_refreshed', models.DateTimeField(default=None, null=True)),
                ('last_used', models.DateTimeField(default=None, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('resource', models.CharField(max_length=512)),
                ('auth_time', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='account.oauthclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
        migrations.CreateModel(
            name='OAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('code_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('redirect_uri', models.CharField(max_length=2048)),
                ('code_challenge', models.CharField(max_length=128)),
                ('scope', models.CharField(blank=True, default='', max_length=200)),
                ('resource', models.CharField(max_length=512)),
                ('auth_time', models.BigIntegerField(default=0)),
                ('expires', models.DateTimeField(db_index=True)),
                ('consumed', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='account.oauthclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_codes', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes', to='account.oauthgrant')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
