"""The environment's KMS key — what `KSMSecrets` models encrypt against.

django-mojo stores some secrets as KMS envelope-encrypted blobs rather than in
the database in the clear: `mojo.models.KSMSecrets` raises outright when
`KMS_KEY_ID` is unset, so a model that inherits it cannot be saved or read at
all without one. The dnsman `Certificate` is the case that matters here — it
holds a TLS private key — which means an environment with no key cannot issue
or hold a certificate, and therefore cannot serve an edge vhost.

DISCOVERY IS BY ALIAS, NOT BY KEY ID. A key id is generated by AWS and is not
derivable from the spec, so a second `apply` that looked for one would have to
keep state to find what the first created. An alias is a name this package
computes (`spec.names()["kms_alias"]`), which makes the alias the resume
anchor and keeps the no-state-file property the rest of the package rests on.

KEY ROTATION IS ENABLED AND DELETION IS NOT OFFERED. AWS schedules a key
deletion 7-30 days out and there is no undo once the window elapses; every
secret ever written against it becomes permanently unreadable. This package
creates and modifies, never deletes, and this is the resource where that rule
is least negotiable.
"""

from mojo.deploy.provision import report
from mojo.deploy.provision import spec as spec_module


STEP = "encryption"

DESCRIPTION = "django-mojo envelope encryption for %s/%s"


def ensure_key(clients, spec, observed, apply=False):
    findings, actions = [], []
    result = report.Result()
    names = spec_module.names(spec)
    alias = names["kms_alias"]
    kms = clients.get("kms")

    existing = observed.get("kms_key_id")
    if existing:
        findings.append(report.existing(
            STEP, "kms.ok", f"{alias} resolves to {existing}"))
        result.set("kms_key_id", existing)
        _converge_rotation(kms, existing, observed, findings, actions, apply)
        return findings, actions, result

    findings.append(report.missing(
        STEP, "kms.missing", f"{alias} does not exist",
        "apply creates a symmetric key with rotation enabled — dnsman "
        "certificates and every other KSMSecrets model refuse to load without "
        "KMS_KEY_ID, so the edge plane cannot serve TLS until it exists"))
    actions.append(report.Action(STEP, "create", alias))
    if not apply:
        return findings, actions, result

    created = report.safe(
        findings, STEP, "kms.create_key",
        lambda: kms.create_key(
            Description=DESCRIPTION % (spec.project, spec.env),
            KeyUsage="ENCRYPT_DECRYPT",
            KeySpec="SYMMETRIC_DEFAULT",
            Tags=[{"TagKey": tag["Key"], "TagValue": tag["Value"]}
                  for tag in spec_module.tag_list(spec, "encryption",
                                                  name=alias)]))
    if created is None:
        return findings, actions, result

    key_id = (created.get("KeyMetadata") or {}).get("KeyId")
    if not key_id:
        findings.append(report.Finding(
            STEP, report.BLIND, "kms.no_key_id",
            "kms.create_key returned no KeyId",
            "re-run apply — nothing was named, so nothing can be adopted"))
        return findings, actions, result

    aliased = report.safe(
        findings, STEP, "kms.create_alias",
        lambda: kms.create_alias(AliasName=alias, TargetKeyId=key_id))
    if aliased is None:
        # The key exists and is unreachable by name. Say exactly that: a
        # silent retry would create a SECOND key on the next run, and the
        # first would keep costing money while holding nothing.
        findings.append(report.manual(
            STEP, "kms.orphan_key",
            f"key {key_id} was created but {alias} could not be pointed at it",
            f"attach the alias by hand — `aws kms create-alias --alias-name "
            f"{alias} --target-key-id {key_id}` — then re-run apply; without "
            f"it the next run creates another key"))
        return findings, actions, result

    report.safe(findings, STEP, "kms.enable_key_rotation",
                lambda: kms.enable_key_rotation(KeyId=key_id))
    result.set("kms_key_id", key_id)
    return findings, actions, result


def _converge_rotation(kms, key_id, observed, findings, actions, apply):
    """Rotation on an adopted key. Unknown is not reported as off."""
    rotating = observed.get("kms_key_rotation")
    if rotating is None:
        return
    if rotating:
        findings.append(report.existing(
            STEP, "kms.rotation_ok", "annual key rotation is enabled"))
        return
    findings.append(report.drift(
        STEP, "kms.rotation_off",
        f"automatic rotation is disabled on {key_id}",
        "apply enables it; rotation re-encrypts nothing, so it is safe on a "
        "key already holding secrets"))
    actions.append(report.Action(STEP, "modify", key_id, "enable rotation"))
    if apply:
        report.safe(findings, STEP, "kms.enable_key_rotation",
                    lambda: kms.enable_key_rotation(KeyId=key_id))
