# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logit', '0006_alter_log_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='gid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['gid'], name='logit_log_gid_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['gid', 'kind'], name='logit_log_gid_kind_idx'),
        ),
    ]
