# Generated by Django 5.2.12 on 2026-04-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logit', '0007_log_gid'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='log',
            new_name='logit_log_gid_c00c73_idx',
            old_name='logit_log_gid_idx',
        ),
        migrations.RenameIndex(
            model_name='log',
            new_name='logit_log_gid_0d5c55_idx',
            old_name='logit_log_gid_kind_idx',
        ),
    ]
