# Generated by Django 5.2.12 on 2026-06-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logit', '0008_rename_logit_log_gid_idx_logit_log_gid_c00c73_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='ip',
            field=models.CharField(default=None, max_length=45, null=True),
        ),
    ]
