# Generated by Django 5.2.16 on 2026-07-27 20:03

import django.db.models.deletion
import mojo.models.rest
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_apikey_override_user_apikey_user'),
        ('filevault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('target_name', models.CharField(blank=True, default='', max_length=200)),
                ('action', models.CharField(db_index=True, max_length=16)),
                ('result', models.CharField(db_index=True, max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('ip', models.CharField(blank=True, db_index=True, default=None, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_access_logs', to='account.group')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_access_logs', to=settings.AUTH_USER_MODEL)),
                ('vault_data', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='filevault.vaultdata')),
                ('vault_file', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to='filevault.vaultfile')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['group', 'created'], name='filevault_v_group_i_39b355_idx'), models.Index(fields=['vault_file', 'created'], name='filevault_v_vault_f_928ea4_idx'), models.Index(fields=['vault_data', 'created'], name='filevault_v_vault_d_785fea_idx'), models.Index(fields=['user', 'created'], name='filevault_v_user_id_5fe19f_idx')],
            },
            bases=(models.Model, mojo.models.rest.MojoModel),
        ),
    ]
